### PR TITLE
Adding new countries and languages that were missing

### PR DESCRIPTION
**Pull request by menarguez**
- New countries: ["pk", "es", "is", "se", "zh"]
 - New languages:["se",
"zh"])

### CODE REVIEW

**Comment by mattlisiv** [comment]
@menarguez I do not see this new additions in the official documentation online. Do you have a source where you found these?

Thanks!

**Comment by menarguez** [comment]
I did so by pulling all sources from the API. As I was using the const as the True value list of candidate items, storage of sources failed. Adding these fixed the problem

**Comment by bsolomon1124** [comment]
These are referenced here:

> https://newsapi.org/docs/endpoints/everything

(Looks like i accidentally duplicated part of this PR in https://github.com/mattlisiv/newsapi-python/pull/44.  Sorry for not looking here first.)

**Comment by mattlisiv** [comment]
Great. At the time, the official documentation did not have the new additions, so I was hesitant to add, but all good now.

Thanks!

**Comment by menarguez** [comment]
It has been a while but thanks for merging this back in the day and thanks for the new additions as well

**Pull request merged**
